#Requires -Version 7.0
<#
.SYNOPSIS
    HCW Agentic Architect — Repository Bootstrap & Auth Configuration
    Writes AGENTS.local.md (gitignored), authenticates CLIs, and validates setup.

.DESCRIPTION
    Run this AFTER install_cli.ps1.
    This script:
      1. Prompts for Azure IDs and writes them to AGENTS.local.md (never committed)
      2. Authenticates: az login, gh auth login
      3. Configures git identity if not set
      4. Validates all expected CLIs are on PATH
      5. Installs/verifies Bicep
      6. Prints a readiness summary

.USAGE
    pwsh ./scripts/configure_repo.ps1
    pwsh ./scripts/configure_repo.ps1 -SkipAzureLogin -SkipGhLogin
#>

[CmdletBinding()]
param(
    [switch]$SkipAzureLogin,
    [switch]$SkipGhLogin,
    [switch]$SkipGitConfig
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

$RepoRoot = Split-Path $PSScriptRoot -Parent
$LocalConfig = Join-Path $RepoRoot 'AGENTS.local.md'

function Write-Step { param([string]$Msg) Write-Host "`n==> $Msg" -ForegroundColor Cyan }
function Write-OK   { param([string]$Msg) Write-Host "  [OK] $Msg" -ForegroundColor Green }
function Write-Fail { param([string]$Msg) Write-Host "  [XX] $Msg" -ForegroundColor Red }
function Write-Warn { param([string]$Msg) Write-Host "  [!!] $Msg" -ForegroundColor Yellow }
function Write-Info { param([string]$Msg) Write-Host "  [..] $Msg" -ForegroundColor Gray }

# ─────────────────────────────────────────────
# 1. Collect local config values
# ─────────────────────────────────────────────
Write-Step "Local configuration (writes to AGENTS.local.md — never committed)"

if (Test-Path $LocalConfig) {
    Write-Warn "AGENTS.local.md already exists. Values below will overwrite it."
    Write-Warn "Press Ctrl+C now to keep existing file, or Enter to continue."
    $null = Read-Host
}

$tenantId       = Read-Host "  Azure Tenant ID       (leave blank to skip)"
$subscriptionId = Read-Host "  Azure Subscription ID (leave blank to skip)"
$subName        = Read-Host "  Azure Subscription Name (e.g. HCW-Dev)"
$region         = Read-Host "  Default Azure Region  [eastus2]"
if ([string]::IsNullOrWhiteSpace($region)) { $region = 'eastus2' }

$gitEmail = Read-Host "  Git email (for git config)"
$gitName  = Read-Host "  Git display name"

# Write AGENTS.local.md
$localContent = @"
# AGENTS.local.md — LOCAL MACHINE CONFIG
# This file is gitignored. Never commit it.
# Generated by configure_repo.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')

## Azure Identity
AZURE_TENANT_ID=$tenantId
AZURE_SUBSCRIPTION_ID=$subscriptionId
AZURE_SUBSCRIPTION_NAME=$subName
AZURE_DEFAULT_REGION=$region

## GitHub
GITHUB_ORG=saulpatinojr
GITHUB_REPO=HCW-Agentic_Architect

## Developer Identity
GIT_EMAIL=$gitEmail
GIT_NAME=$gitName
"@

$localContent | Set-Content -Path $LocalConfig -Encoding UTF8
Write-OK "AGENTS.local.md written to $LocalConfig"

# Verify .gitignore covers it
$gitignorePath = Join-Path $RepoRoot '.gitignore'
if (Test-Path $gitignorePath) {
    $gitignoreContent = Get-Content $gitignorePath -Raw
    if ($gitignoreContent -notmatch 'AGENTS\.local\.md') {
        Write-Warn "AGENTS.local.md is NOT in .gitignore — adding now"
        Add-Content -Path $gitignorePath -Value "`nAGENTS.local.md"
        Write-OK "Added AGENTS.local.md to .gitignore"
    } else {
        Write-OK "AGENTS.local.md is already in .gitignore"
    }
} else {
    Write-Warn ".gitignore not found at repo root"
}

# ─────────────────────────────────────────────
# 2. Git identity
# ─────────────────────────────────────────────
if (-not $SkipGitConfig) {
    Write-Step "Git identity"
    if (-not [string]::IsNullOrWhiteSpace($gitEmail)) {
        git config --global user.email $gitEmail
        Write-OK "git config user.email = $gitEmail"
    }
    if (-not [string]::IsNullOrWhiteSpace($gitName)) {
        git config --global user.name $gitName
        Write-OK "git config user.name = $gitName"
    }
    # Recommended global git settings
    git config --global core.autocrlf input
    git config --global push.default current
    git config --global pull.rebase false
    git config --global init.defaultBranch main
    Write-OK "Global git settings applied (autocrlf=input, push.default=current)"
}

# ─────────────────────────────────────────────
# 3. Azure CLI login
# ─────────────────────────────────────────────
if (-not $SkipAzureLogin) {
    Write-Step "Azure CLI authentication"
    if (Get-Command az -ErrorAction SilentlyContinue) {
        Write-Info "Running: az login (browser will open)"
        az login
        if (-not [string]::IsNullOrWhiteSpace($subscriptionId)) {
            az account set --subscription $subscriptionId
            Write-OK "Default subscription set to $subscriptionId"
        }
        # Install/update Bicep
        az bicep install
        Write-OK "Bicep installed/updated"
    } else {
        Write-Fail "az CLI not found — run install_cli.ps1 first"
    }
}

# ─────────────────────────────────────────────
# 4. GitHub CLI login
# ─────────────────────────────────────────────
if (-not $SkipGhLogin) {
    Write-Step "GitHub CLI authentication"
    if (Get-Command gh -ErrorAction SilentlyContinue) {
        Write-Info "Running: gh auth login"
        gh auth login
        Write-OK "GitHub CLI authenticated"
    } else {
        Write-Fail "gh CLI not found — run install_cli.ps1 first"
    }
}

# ─────────────────────────────────────────────
# 5. Validate all CLIs
# ─────────────────────────────────────────────
Write-Step "CLI validation"
$clis = @(
    @{ Cmd = 'az';           Name = 'Azure CLI' },
    @{ Cmd = 'terraform';    Name = 'Terraform' },
    @{ Cmd = 'gh';           Name = 'GitHub CLI' },
    @{ Cmd = 'git';          Name = 'Git' },
    @{ Cmd = 'node';         Name = 'Node.js' },
    @{ Cmd = 'npm';          Name = 'npm' },
    @{ Cmd = 'pwsh';         Name = 'PowerShell 7+' },
    @{ Cmd = 'claude';       Name = 'Claude Code CLI' },
    @{ Cmd = 'codex';        Name = 'OpenAI Codex CLI' },
    @{ Cmd = 'gemini';       Name = 'Gemini CLI' },
    @{ Cmd = 'code';         Name = 'VS Code CLI' },
    @{ Cmd = 'docker';       Name = 'Docker CLI' },
    @{ Cmd = 'antigravity';  Name = 'Antigravity CLI' }
)

$allPassed = $true
foreach ($cli in $clis) {
    if (Get-Command $cli.Cmd -ErrorAction SilentlyContinue) {
        $ver = try { & $cli.Cmd --version 2>&1 | Select-Object -First 1 } catch { 'installed' }
        Write-OK "$($cli.Name): $ver"
    } else {
        Write-Warn "$($cli.Name) ($($cli.Cmd)) not found on PATH"
        $allPassed = $false
    }
}

# ─────────────────────────────────────────────
# 6. Summary
# ─────────────────────────────────────────────
Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
if ($allPassed) {
    Write-Host " All CLIs validated. Repo is ready!" -ForegroundColor Green
} else {
    Write-Host " Setup complete with warnings." -ForegroundColor Yellow
    Write-Host " Some CLIs are missing — see [!!] items above." -ForegroundColor Yellow
}
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Open workspace in VS Code:    code ." -ForegroundColor Yellow
Write-Host "Open workspace in Antigravity: antigravity open ." -ForegroundColor Yellow
Write-Host ""
